### ISSUE TITLE
Erlang is missing from all languageserver tables

### ISSUE THREAD

**Issue by peerst** [erlide/sourcer#16]
Elixir is already there but no entry for Erlang:

https://langserver.org/#implementations-server

Adding to the site can be done through:

https://github.com/langserver/langserver.github.io

The same goes for Microsofts own table:

https://microsoft.github.io/language-server-protocol/implementors/servers/

Which can be added to by PR against:

https://github.com/Microsoft/language-server-protocol/blob/gh-pages/_implementors/servers.md

**Comment by vladdu** [comment]
Thanks, I will add that. I didn't yet because it wasn't quite functional,
but it's time now :-)
regards,
Vlad

**Comment by vladdu** [comment]
PR against both sites have been created.
