### ISSUE TITLE
STDIO input?

### ISSUE THREAD

**Issue by subsetpark** [erlide/sourcer#17]
The kakoune lsp editor integration https://github.com/ul/kak-lsp expects to be able to  send input to its servers via standard io. Do you have any intention of exposing that as an option as well as TCP?

**Comment by vladdu** [comment]
Yes, but I haven't planned anything yet.

**Comment by vladdu** [comment]
I have implemented this, but without testing it a lot. If you would like to try it out, you can use the binary script at https://ci.erlide.org/job/sourcer-erlang/job/master/21/artifact/_build/default/bin/erlang_ls

Start the server with a "--transport stdio" argument.

**Comment by vladdu** [comment]
This is done, if there are problems, please open new issues.
