### ISSUE TITLE
run dialyzer in the build

### ISSUE THREAD

**Issue by vladdu** [erlide/sourcer#2]
- create a Makefile that calls dialyzer
- change build commands for travis
- create default PLTs on erlide.org and wget them when building, to shorten build times

**Comment by tuncer** [comment]
Creating a custom PLT via `rebar build-plt` on Travis-CI should be fast enough for the project's size. So, I'd suggest to start with `rebar build-plt` and `rebar dialyze`. You might run into issues like absolute paths in the PLT, if you want to cache it, so caching may have to be Travis-CI-specific.

**Comment by ghost** [comment]
Creating a custom PLT via `rebar build-plt` on Travis-CI should be fast enough for the project's size. So, I'd suggest to start with `rebar build-plt` and `rebar dialyze`. You might run into issues like absolute paths in the PLT, if you want to cache it, so caching may need to be Travis-CI-specific.

**Comment by vladdu** [comment]
Thanks for pointing that out, Tuncer. I didn't follow the latest rebar release notes and only by looking at the wiki and searching on google[*] I didn't know about the new dialyzer support. 

Interestingly, only "rebar dialyze" (not "rebar dialyzer") brings up a link to the 2.6 announcement.

**Comment by ghost** [comment]
If you have time, feel free to extend the wiki page. Also, you can always use `rebar --commands/-c` to see built-in commands.

**Comment by vladdu** [comment]
Yes, but since I hadn't updated to 2.6.0, listing the commands doesn't help. :wink:

**Comment by ghost** [comment]
2.6.1 is out :).

**Comment by vladdu** [comment]
Fixed. Travis has an older version of rebar.
