### ISSUE TITLE
[Question] What is the difference between this project and erlang_ls?

### ISSUE THREAD

**Issue by revington** [erlide/sourcer#28]
I was looking for an erlang language server and found this project and this other one https://github.com/erlang-ls/erlang_ls
Can you explain the differences?

thx

**Comment by vladdu** [comment]
Hi! This is an earlier project and currently not actively maintained. It is based on the code for the Eclipse Erlang plugin.

**Comment by revington** [comment]
Ah! Thanks for a quick response!
